
DROP SEQUENCE MEMBERSEQ;   --나중에 문제가 있어서 다시 만들어야 하거나 혹은 이미 저 테이블 이름이 사용되고 있을 것 같을 때 전체선택해서 실행하면 드롭하고 크리에이트 한다.
DROP TABLE MEMBER;

CREATE SEQUENCE MEMBERSEQ;
-- 회원가입
-- 번호, 이름, 나이, 성별, 지역, 직업, 전화번호, 이메일
CREATE TABLE MEMBER(
	M_NO NUMBER PRIMARY KEY,
	M_NAME VARCHAR2(50) NOT NULL,
	M_AGE NUMBER NOT NULL,
	M_GENDER VARCHAR2(2) CHECK(M_GENDER IN ('M', 'F')) NOT NULL,
	M_LOCATION VARCHAR2(100),
	M_JOB VARCHAR2(100),
	M_TEL VARCHAR2(20),
	M_EMAIL VARCHAR2(20)
);

INSERT INTO MEMBER
VALUES (MEMBERSEQ.NEXTVAL, '김관리', 100, 'M', '강남', '관리자', '010-1111-1111', 'ADMIN@ADMIN.COM');

INSERT INTO MEMBER
VALUES (MEMBERSEQ.NEXTVAL, '홍길동', 50, 'F', '강북', '의적', '010-2222-2222', 'HONG@HONG.COM');

SELECT M_NO, M_NAME, M_AGE, M_GENDER, M_LOCATION, M_JOB, M_TEL, M_EMAIL
FROM MEMBER
ORDER BY M_NO DESC;




